#!/usr/bin/env bash
set -e

# ------------------------------------------------------------
# Full Career‑Ops bulk pipeline (one‑click)
#   1️⃣ Evaluate each pending job in data/pipeline.md using Gemini
#   2️⃣ Generate an ATS‑optimized PDF for each report
#   3️⃣ Pre‑fill each application form (Playwright) – pause before final Submit
# ------------------------------------------------------------

# Ensure required tools are available
if ! command -v node >/dev/null; then
  echo "Node.js is required but not found. aborting." >&2
  exit 1
fi

# Extract URLs from pipeline that are marked as processed (- [x])
urls=$(grep '^\s*- \[x\]' data/pipeline.md | grep -Eo '(https?://[^[:space:]]+)')

if [ -z "$urls" ]; then
  echo "No processed URLs found in data/pipeline.md. Nothing to do." >&2
  exit 0
fi

# ------------------------------------------------------------
# Step 1 – Evaluate each job and save a report
# ------------------------------------------------------------
for url in $urls; do
  echo "[Eval] Processing $url"
  
  # Fetch JD text from the URL using Jina AI reader
  jd_text=$(curl -s "https://r.jina.ai/$url")
  
  if [ -z "$jd_text" ] || [[ "$jd_text" == *"Error"* ]]; then
    echo "⚠️ Failed to fetch JD text for $url. Skipping..."
    continue
  fi

  # Pass the fetched text to Gemini evaluator
  node gemini-eval.mjs "$jd_text"
done

# ------------------------------------------------------------
# Step 2 – Generate PDFs for all newly‑created reports
# ------------------------------------------------------------
# Find all HTML files generated by the template (they are located in output/)
for html in output/*.html; do
  [ -e "$html" ] || continue
  pdf="${html%.html}.pdf"
  echo "[PDF] Generating $pdf from $html"
  node generate-pdf.mjs "$html" "$pdf" --format=letter
done

# Step 3 skipped in bulk mode. I will handle applications manually using the browser tool.
echo "✅ All evaluations and PDFs completed."

echo "✅ All steps completed."
